modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPLv3"

[[mods]]
modId = "abs"
version = "1.0.0"

displayName = "Absolute"
logoFile = "absolute_banner_transparent.png"
credits = "debug61, McWinston"
authors = "debug61"
description = '''
Adding a path to find an absolute in everything!
'''

[[dependencies.abs]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
